export const ADD_TASK = 'ADD_TASK'
export const DELETE_TASK = 'DELETE_TASK'
export const UPDATE_TASK = 'UPDATE_TASK'
export const SET_TASKS = 'SET_TASKS'

export const ADD_LIST = 'ADD_LIST'
export const DELETE_LIST = 'DELETE_LIST'
export const UPDATE_LIST = 'UPDATE_LIST'
export const SET_LISTS = 'SET_LISTS'

export const GET_INFO_ASYNC = {
  SUCCESS: 'GET_INFO_ASYNC_SUCCESS',
  FAILURE: 'GET_INFO_ASYNC_FAILURE',
  PENDING: 'GET_INFO_ASYNC_PENDING',
}
